import axios from "axios";
import { AsyncStorage } from "react-native";

const instance = axios.create({
  // Change the Base URL according to URL generated by ngrok
  baseURL: " https://f1d6667d133b.ngrok.io",
});
instance.interceptors.request.use(
  async (config) => {
    try {
      const token = await AsyncStorage.getItem("token");
      if (token) {
        config.headers.Authorization = `JWT ${token}`;
      }
      return config;
    } catch (err) {
      console.log(err);
    }
  },
  (err) => {
    console.log(err);
    return Promise.reject(err);
  }
);

export default instance;
